# Generated by Django 4.0.5 on 2022-07-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comany_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'مستخدمون المنشات', 'verbose_name_plural': 'مستخدمون المنشات'},
        ),
    ]
