# Generated by Django 4.0.5 on 2022-07-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees_company',
            fields=[
                ('sub_data_emp', models.CharField(blank=True, max_length=50, null=True, verbose_name='بيانات الاشتراك فى مدد')),
                ('name_emp', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الموظف')),
                ('name_father_emp', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الاب')),
                ('name_gfather_emp', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الجد')),
                ('family', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم العائلة')),
                ('roles', models.CharField(choices=[('الهوية الوطنية', 'الهوية الوطنية'), ('الاقامة', 'الاقامة'), ('جواز السفر', 'جواز السفر')], max_length=100, verbose_name='نوع الهوية')),
                ('number_identity', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name=' رقم الهوية')),
                ('typ_credit', models.CharField(blank=True, max_length=100, null=True, verbose_name='نوع الفيزا')),
                ('nationality', models.CharField(max_length=100, verbose_name='الجنسية')),
                ('religion', models.CharField(blank=True, max_length=100, null=True, verbose_name='الديانة')),
                ('gender', models.CharField(choices=[('ذكر', 'ذكر'), ('انثى', 'انثى')], max_length=50, verbose_name='الجنس')),
                ('birth_date', models.CharField(blank=True, max_length=200, null=True, verbose_name='تاريخ الميلاد')),
                ('disability', models.CharField(blank=True, max_length=50, null=True, verbose_name='عجز')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الالكترونى')),
                ('id_country', models.CharField(blank=True, max_length=100, null=True, verbose_name='رمز البلد')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الجوال')),
                ('number_build', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المبنى')),
                ('name_street', models.CharField(blank=True, max_length=20, null=True, verbose_name='اسم الشارع')),
                ('name_center', models.CharField(blank=True, max_length=20, null=True, verbose_name='اسم الحى')),
                ('country', models.CharField(blank=True, max_length=20, null=True, verbose_name='البلد')),
                ('city', models.CharField(blank=True, max_length=20, null=True, verbose_name='المدينة')),
                ('postal_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='الرمز البريدى')),
                ('gradution', models.CharField(blank=True, max_length=50, null=True, verbose_name='المؤهل العلمى')),
                ('join_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='تاريخ الالتحاق')),
                ('type_employe', models.CharField(blank=True, max_length=200, null=True, verbose_name='نوع التوظيف')),
                ('job_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='المسمى الوظيفى')),
                ('carrer_ladder', models.CharField(blank=True, max_length=200, null=True, verbose_name='السلم الوظيفى')),
                ('status_job', models.CharField(default='نشط', max_length=200, verbose_name='الحالة الوظيفية')),
                ('date_end_contract', models.CharField(blank=True, max_length=200, null=True, verbose_name='تاريخ انهاء العقد')),
                ('name_supervisor', models.CharField(blank=True, max_length=300, null=True, verbose_name='اسم المشرف')),
                ('payment_method', models.CharField(blank=True, choices=[('تحويل مصرفى', 'تحويل مصرفى'), ('شيك', 'شيك'), ('نقدا', 'نقدا')], max_length=100, null=True, verbose_name='طريقة الدفع')),
                ('iban', models.CharField(blank=True, max_length=300, null=True, verbose_name='رقم الايبان')),
                ('basic_wage', models.IntegerField(max_length=10, verbose_name='الاجر الاساسى')),
                ('month_housing_instead', models.IntegerField(max_length=10, verbose_name='بدل السكن الشهرى')),
                ('transport_instead', models.IntegerField(max_length=10, verbose_name='بدل النقل')),
                ('medical_insurance_date', models.CharField(blank=True, max_length=200, null=True, verbose_name='تاريخ التامين الطبى')),
                ('medical_insurance_end_date', models.CharField(blank=True, max_length=200, null=True, verbose_name='تاريخ انتهاء التامين الطبى')),
                ('number_polecy_insurance', models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم بوليصة التامين الطبى')),
                ('number_passoort', models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم الجواز')),
                ('release_date_passport', models.CharField(blank=True, max_length=200, null=True, verbose_name='تاريخ اصدار الجواز')),
                ('end_date_passport', models.CharField(blank=True, max_length=200, null=True, verbose_name='تاريخ انتهاء الجواز')),
                ('num_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='num_orgnizations', to='company.companies', verbose_name='المنشأة')),
            ],
            options={
                'verbose_name': ' موظفون المنشآت',
                'verbose_name_plural': 'موظفون المنشآت',
            },
        ),
    ]
