# Generated by Django 4.0.5 on 2022-07-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=100, verbose_name='اسم المنشأة')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان التقرير')),
                ('unified_number', models.CharField(max_length=100, verbose_name='الرقم الموحد')),
                ('upload', models.FileField(upload_to='uploads/', verbose_name='التقرير')),
                ('date', models.DateField(blank=True, null=True, verbose_name='التاريخ')),
            ],
            options={
                'verbose_name': 'التقارير',
                'verbose_name_plural': 'التقارير',
            },
        ),
    ]
