# Generated by Django 4.0.5 on 2022-07-04 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='clerk',
            fields=[
                ('name', models.CharField(max_length=200, verbose_name='اسم الموظف')),
                ('number_subscribtion', models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم الاشتراك')),
                ('id_emp', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name=' رقم الهوية')),
                ('phone', models.PositiveIntegerField(blank=True, max_length=300, null=True, unique=True, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='البريد الالكترونى')),
                ('iban', models.CharField(max_length=200, unique=True, verbose_name='الايبان')),
                ('start_date', models.DateField(verbose_name='تاريخ الالتحاق')),
                ('code_bank', models.CharField(blank=True, max_length=50, null=True, verbose_name='رمز البنك')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفى')),
                ('subscriber_number', models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم المشترك')),
                ('roles_pack', models.CharField(choices=[('نشط', 'نشط'), ('غير نشط', 'غير نشط')], max_length=50, verbose_name='حالة الباقة')),
                ('roles_emp', models.CharField(choices=[('سارى', 'سارى'), ('ملغى من قبل المنشأة', 'ملغى من قبل المنشأة'), ('فى انتظار موافقة الموظف', 'فى انتظار موافقة الموظف')], max_length=50, verbose_name='حالة الموظف')),
                ('num_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nm_company', to='company.companies', verbose_name='المنشأة')),
                ('package_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nm_package', to='package.packages', verbose_name='الباقة')),
            ],
            options={
                'verbose_name': 'الموظفون',
                'verbose_name_plural': 'الموظفون',
            },
        ),
    ]
