# Generated by Django 4.0.5 on 2022-07-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_task', models.CharField(max_length=400, verbose_name='عنوان المهمة')),
                ('employee_name', models.CharField(blank=True, max_length=400, null=True, verbose_name='الموظف')),
                ('path', models.CharField(blank=True, max_length=400, null=True, verbose_name='المسار')),
                ('company', models.CharField(blank=True, max_length=400, null=True, verbose_name='المنصة')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بداية المهمة')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية  المهمة')),
                ('describtion', models.TextField(blank=True, null=True, verbose_name='وصف المهمة')),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploads_taska/', verbose_name='المرفقات')),
            ],
            options={
                'verbose_name': 'المهمات',
                'verbose_name_plural': 'المهمات',
            },
        ),
    ]
