# Generated by Django 4.0.5 on 2022-07-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('name_company', models.CharField(max_length=100, verbose_name='اسم المنشأة')),
                ('num_company', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='رقم المنشأة')),
                ('unified_national_number', models.CharField(max_length=50, unique=True, verbose_name='الرقم الوطنى الموحد')),
                ('num_selling_record', models.CharField(max_length=200, verbose_name='رقم ترخيص السجل التجارى')),
                ('location_selling_record', models.CharField(blank=True, max_length=200, null=True, verbose_name='مصدر ترخيص السجل التجارى')),
                ('end_date_selling_record', models.CharField(blank=True, max_length=200, null=True, verbose_name='تاريخ انتهاء ترخيص السجل التجارى')),
                ('num_baladia_license', models.CharField(blank=True, max_length=200, null=True, verbose_name='رقم ترخيص البلدية')),
                ('location_baladia_license', models.CharField(blank=True, max_length=200, null=True, verbose_name='مصدر ترخيص البلدية')),
                ('end_date_baladia_license', models.CharField(blank=True, max_length=200, null=True, verbose_name='تاريخ انتهاء ترخيص البلدية')),
                ('unified_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='الرقم الموحد')),
                ('nationality_establishment', models.CharField(max_length=50, verbose_name='جنسية المنشأة')),
                ('date_founding', models.CharField(max_length=100, verbose_name='تاريخ بداية المنشأة')),
                ('main', models.CharField(blank=True, max_length=50, null=True, verbose_name='رئيسى')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='المدينة')),
                ('status', models.CharField(max_length=50, verbose_name='الحالة')),
                ('adress_national', models.CharField(blank=True, max_length=100, null=True, verbose_name='العنوان الوطنى')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='التليفون')),
            ],
            options={
                'verbose_name': 'المنشآت',
                'verbose_name_plural': 'المنشآت',
            },
        ),
    ]
